---
title: "Twitter_Covid"
author: "Ons Hosni"
date: "29/04/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```



```{r}
library(rtweet)
library(httpuv)
library(tidyverse)
library(ggplot2)
library(tokenizers)
library(tidytext)
library(dplyr)
library(SnowballC)
library(RColorBrewer)
library(wordcloud)
library(wordcloud2)
library(tidyr)
```


```{r }
#### Extract tweets  

Covid<-search_tweets("#covid19", 
                     n = 10000, 
                     include_rts = TRUE, 
                     lang = "en")
```

```{r}
################## plot of common words recent tweets about Covid19

Covid$text<-gsub("https\\S*", "", Covid$text) 
Covid$text<-gsub("@\\S*", "", Covid$text) 
Covid$text<-gsub("amp", "", Covid$text) 
Covid$text<-gsub("[\r\n]", "", Covid$text)
Covid$text<-gsub("[[:punct:]]", "", Covid$text)
undesirable_words<-c("still","less","can","could","should","the", "will", 
    "The", "also", "that", "and", "for", "in", "is", "it", "not", "to","get","am","are","of","from")

tweets_words <- Covid %>%
  select(text) %>%
  unnest_tokens(word, text) %>%
  anti_join(get_stopwords()) %>%
  filter(!word %in% undesirable_words)

words <- tweets_words %>% 
      count(word, sort=TRUE)
#str(words)
```

```{r}
#creating the plot
plot1<-wordcloud2(data=words, size=1.6, color='random-dark')

######################## Popular tweets

t1<-Covid[,c("retweet_name","retweet_count","text")] %>%
      group_by(retweet_name,text) %>%
      summarise(retweet_count=sum(retweet_count)) %>%
      arrange(desc(retweet_count))
t1<-as.data.frame(t1)
```

```{r}
####################### Sentimental Analysis of common words 


bing <- get_sentiments("bing")

bing_word_counts <- tweets_words%>%
  inner_join(bing) %>%
  count(word, sentiment, sort = TRUE)

plot2<-bing_word_counts %>%
  filter(n > 150) %>%
  mutate(n = ifelse(sentiment == "negative", -n, n)) %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n, fill = sentiment)) +
  geom_col() +
  coord_flip() +
  labs(y = "Contribution to sentiment", title="Sentimental Analysis of common words")
plot2
```

```{r, fig.height=7, fig.width=16}

######################## frequency of covid19 tweets with different languages

tw<-search_tweets("#covid19", 
                  n = 10000, 
                  include_rts = TRUE)

lan<-tw %>%
  group_by(lang)%>%
  summarise(count=n()) %>%
  arrange(desc(count)) %>%
  top_n(10,count)

lan<-lan %>%
  mutate(Language=c("English","Spanish","French","Portuguese",
                    "Italian","undefined","German","Japanese","Catalan(Spain)","Arabic"))

plot3<-ggplot(lan,aes(x=Language,y=count,fill=Language))+geom_col()+
  labs(title="Graph of common top 10 languages on Covid19 twitter data ")


plot3
```


